on: [push]

jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: deploy
    steps:
     - uses: actions/checkout@master
    
     - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
        
     - name: Build Project
        run: |
          npm install
          npm run build --if-present
        
     - name: List output files
       run: ls
        - name: Checkout
          uses: actions/checkout@v2
        - name: deploy file
          uses: wlixcc/SFTP-Deploy-Action@v1.0
          with:
            username: 'root'
            server: '137.184.126.33'
            ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} 
            local_path: './build/*'
            remote_path: '/var/www/'
            args: '-o ConnectTimeout=5'
